### PR TITLE
Revert "Adds pyenv to testing"

### PR DESCRIPTION
**Pull request by birdofpreyru**
Reverts ConsenSys/mythril-ci#2

@joshuata I revert your PR, as when I try to re-build container after that, it fails with the following error:
image

### CODE REVIEW

**Comment by joshuata** [comment]
I have no idea what the difference is but it works on my machine. Try re-pulling the base `ubuntu/rolling` box.

**Comment by birdofpreyru** [comment]
@joshuata yeap, I'm going to carefully look into this within the next few days.

**Comment by joshuata** [comment]
Good. I just pulled the latest and built it on my machine, so I can't find a difference. Also, it might be a good idea to rename the image to `mythril-ci` or something like that, and make the image auto-build on docker hub.

**Comment by birdofpreyru** [comment]
@joshuata ok, ready: 8790a33970487f37dafd701308d6ba3be111d3e5

The problem for me was that you specified `hkps://keyserver.ubuntu.com` as the keyserver in few places.
Replacing that by `hkp://keyserver.ubuntu.com:80` solved the build issue for me.

On the way I replaced the way to install NodeJS and Heroku back to the commands recommended in their docs. I wonder, is there any particular reason why you wanted to install them in a different way, explicitly adding their keys and apt repos? I guess, instructions from docs do the same, under the hood, but I feel a bit better about them cause they are (i) straight from docs; (ii) occupy less space in Dockerfile.

Yeah, the image is available at Dockerhub as `birdofpreyru/mythril-integration-tests:0.0.3`
Later tonight I'll update mythril and mythril-api repos to use it

**Comment by joshuata** [comment]
I went with the manual install since it is more deterministic. I know a lot of people are uncomfortable with unverifiable shell scripts Since they can be used to compromise a system.

**Pull request merged**
